--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2026-09-11 13:16:17


CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4934 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16398)
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    account_number character varying(255),
    account_status character varying(255),
    account_type character varying(255),
    address character varying(255),
    branch_name character varying(255),
    current_balance numeric(38,2),
    customer_name character varying(255),
    email character varying(255),
    mobile_number character varying(255),
    opening_date date,
    user_id bigint,
    CONSTRAINT accounts_account_status_check CHECK (((account_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'CLOSED'::character varying])::text[]))),
    CONSTRAINT accounts_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['SAVINGS'::character varying, 'CURRENT'::character varying])::text[])))
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16397)
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16419)
-- Name: fixed_deposit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fixed_deposit (
    id bigint NOT NULL,
    deposit_amount double precision,
    deposit_date date,
    fd_number character varying(255),
    interest_rate double precision,
    maturity_amount double precision,
    maturity_date date,
    tenure_years integer,
    user_id bigint
);


ALTER TABLE public.fixed_deposit OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16418)
-- Name: fixed_deposit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fixed_deposit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fixed_deposit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16425)
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    available_balance double precision,
    transaction_amount double precision,
    transaction_date timestamp(6) without time zone,
    transaction_id character varying(255),
    transaction_type character varying(255),
    account_id bigint,
    CONSTRAINT transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['CREDIT'::character varying, 'DEBIT'::character varying])::text[])))
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16424)
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16389)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255),
    role character varying(255),
    username character varying(255),
    full_name character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16388)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4924 (class 0 OID 16398)
-- Dependencies: 220
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.accounts VALUES (2, 'AC386136266', 'ACTIVE', 'SAVINGS', 'Datta Mandir Wakad', 'Wakad', 0.00, 'Chaitanya Mahajan', 'chaitanyaMahajan@gmail.com', '8584868595', '2026-08-04', NULL);
INSERT INTO public.accounts VALUES (3, 'AC746262448', 'ACTIVE', 'SAVINGS', 'Talawade', 'Wakad', 0.00, 'Chaitanya Mahajan', 'chaitanyaMahajan1@gmail.com', '9999900000', '2026-08-04', NULL);
INSERT INTO public.accounts VALUES (5, 'AC733238058', 'ACTIVE', 'SAVINGS', 'Raver', 'Savda', 3890.00, 'Sanket Sonar', 'SanketSoni@gmail.com', '9673968449', '2026-08-31', NULL);
INSERT INTO public.accounts VALUES (4, 'AC577212392', 'ACTIVE', 'SAVINGS', 'Khandwa', 'Savda', 75288.00, 'Siddhu', 'sidhhu@gmail.com', '8888888888', '2026-08-30', NULL);
INSERT INTO public.accounts VALUES (6, 'ACC20260911123714445', 'ACTIVE', 'SAVINGS', 'Khandwa', 'Savda', 3499.41, 'Siddhu', 'Siddhu110911@gmail.com', '9977662698', '2026-09-11', NULL);


--
-- TOC entry 4926 (class 0 OID 16419)
-- Dependencies: 222
-- Data for Name: fixed_deposit; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.fixed_deposit VALUES (1, 100000, '2026-08-30', 'FD226809', 6.5, 106500, '2027-08-30', 1, 13);
INSERT INTO public.fixed_deposit VALUES (2, 300000, '2026-08-30', 'FD336458', 7, 367512.9, '2029-08-30', 3, 13);
INSERT INTO public.fixed_deposit VALUES (3, 11000, '2026-08-31', 'FD778754', 6.5, 11715, '2027-08-31', 1, 13);
INSERT INTO public.fixed_deposit VALUES (4, 11000, '2026-08-31', 'FD188034', 7, 13475.473000000002, '2029-08-31', 3, 13);


--
-- TOC entry 4928 (class 0 OID 16425)
-- Dependencies: 224
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.transactions VALUES (2, 5000, 5000, '2026-08-30 16:47:00.471862', 'TXN001', 'CREDIT', 4);
INSERT INTO public.transactions VALUES (3, 50000, 50000, '2026-08-30 19:24:40.332049', 'TXN1788098080330', 'CREDIT', 4);
INSERT INTO public.transactions VALUES (4, 49500, 500, '2026-08-30 19:25:00.803754', 'TXN1788098100803', 'DEBIT', 4);
INSERT INTO public.transactions VALUES (5, 42500, 7000, '2026-08-30 19:26:41.043155', 'TXN1788098201043', 'DEBIT', 4);
INSERT INTO public.transactions VALUES (6, 39500, 3000, '2026-08-30 19:26:49.741376', 'TXN1788098209741', 'DEBIT', 4);
INSERT INTO public.transactions VALUES (7, 49500, 10000, '2026-08-30 19:27:05.455071', 'TXN1788098225455', 'CREDIT', 4);
INSERT INTO public.transactions VALUES (8, 62499, 12999, '2026-08-30 19:27:46.352757', 'TXN1788098266352', 'CREDIT', 4);
INSERT INTO public.transactions VALUES (9, 63499, 1000, '2026-08-30 19:29:00.740221', 'TXN1788098340740', 'CREDIT', 4);
INSERT INTO public.transactions VALUES (10, 65499, 2000, '2026-08-30 19:29:06.413513', 'TXN1788098346412', 'CREDIT', 4);
INSERT INTO public.transactions VALUES (11, 68499, 3000, '2026-08-30 19:29:12.193184', 'TXN1788098352193', 'CREDIT', 4);
INSERT INTO public.transactions VALUES (12, 63499, 5000, '2026-08-30 19:29:23.637082', 'TXN1788098363637', 'DEBIT', 4);
INSERT INTO public.transactions VALUES (13, 48499, 15000, '2026-08-30 19:29:30.49452', 'TXN1788098370494', 'DEBIT', 4);
INSERT INTO public.transactions VALUES (14, 33499, 15000, '2026-08-30 19:29:42.094382', 'TXN1788098382094', 'DEBIT', 4);
INSERT INTO public.transactions VALUES (15, 63499, 30000, '2026-08-30 19:32:40.154979', 'TXN1788098560154', 'CREDIT', 4);
INSERT INTO public.transactions VALUES (16, 4445, 555, '2026-08-31 11:14:44.842389', 'TXN1788155084842', 'DEBIT', 5);
INSERT INTO public.transactions VALUES (17, 3890, 555, '2026-08-31 14:20:22.446062', 'TXN1788166222446', 'DEBIT', 5);
INSERT INTO public.transactions VALUES (18, 75843, 12344, '2026-08-31 14:20:42.382564', 'TXN1788166242382', 'CREDIT', 4);
INSERT INTO public.transactions VALUES (19, 75288, 555, '2026-08-31 14:21:38.827314', 'TXN1788166298827', 'DEBIT', 4);
INSERT INTO public.transactions VALUES (20, 500, 500, '2026-09-11 12:43:01.834015', 'TXN1789110781832', 'CREDIT', 6);
INSERT INTO public.transactions VALUES (21, 5500, 5000, '2026-09-11 12:48:20.953363', 'TXN1789111100953', 'CREDIT', 6);
INSERT INTO public.transactions VALUES (22, 5000, 500, '2026-09-11 12:48:26.584277', 'TXN1789111106584', 'DEBIT', 6);
INSERT INTO public.transactions VALUES (23, 4500, 500, '2026-09-11 12:48:37.55395', 'TXN1789111117553', 'DEBIT', 6);
INSERT INTO public.transactions VALUES (24, 4000, 500, '2026-09-11 12:49:39.509016', 'TXN1789111179509', 'DEBIT', 6);
INSERT INTO public.transactions VALUES (25, 3499.41, 500.59, '2026-09-11 12:51:51.276428', 'TXN1789111311276', 'DEBIT', 6);


--
-- TOC entry 4922 (class 0 OID 16389)
-- Dependencies: 218
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users VALUES (7, 'sanketsonar507@gmail.com', '$2a$10$.OIB1dDeF5.fjF9GsZVVEullp/L9l1SIy26ICs5M9OCimCDG/qRlC', 'ADMIN', NULL, 'Sanket Sonar');
INSERT INTO public.users VALUES (8, 'chaitanyaMahajan@gmail.com', '$2a$10$cuFb4dHidyLh9xpxl6CVneuAQl.Eq5G6SGWC9DTlidH9hbbcWh0XK', 'CUSTOMER', NULL, 'Chaitanya Mahajan');
INSERT INTO public.users VALUES (9, 'shubhamgarge@gmail.com', '$2a$10$QrZesAXqEPgOmT0s1cpNgOaokrP3ONF2KoBd25BvVaT2Q.YOzLM.i', 'CUSTOMER', NULL, 'Shubham Garge');
INSERT INTO public.users VALUES (10, 'sandeep@gmail.com', '$2a$10$eEQRA.yCan4RNJzI3olq/uaET/152Tzsn7oWRG8AIbYMCvNtaOXwG', 'CUSTOMER', NULL, 'Sandeep Mishra');
INSERT INTO public.users VALUES (11, 'sanketsonar5071@gmail.com', '$2a$10$69Dky5xsXhpP/eUAgd48TO7G8VzICknuuOgjIflvlXLwcaZoejiGa', 'ADMIN', NULL, 'Sanket Sonar1');
INSERT INTO public.users VALUES (12, 'SanketSonar@gmail.com', '$2a$10$DF9xVVYd3JHYYTHkvrlUhetJ9TqrWmXT0tjQ3cJzXVKDY4hECTU4O', 'ADMIN', NULL, 'Sanket');
INSERT INTO public.users VALUES (13, 'Siddhu@gmail.com', '$2a$10$JgDz7HMumEx7yKRAXk1A2.8wqZFF6A0Dd4RUSjB9.mY3KquvpeDIO', 'ADMIN', NULL, 'Siddhesh Soni');
INSERT INTO public.users VALUES (14, 'SanketSoni@gmail.com', '$2a$10$MB922eMZw2E/ATbY4QW4nuJz79uo19ARHOA.HuhLGOjxhkOaaW0nS', 'ADMIN', NULL, 'Sanket Soni');
INSERT INTO public.users VALUES (15, 'Siddhu110911@gmail.com', '$2a$10$q1ZG9OejN91jTuxC3pAhxeFhkNTeUi5kZjjhoz05DIwwPrmL5N0MK', 'ADMIN', NULL, 'Siddhesh Soni');


--
-- TOC entry 4935 (class 0 OID 0)
-- Dependencies: 219
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_id_seq', 6, true);


--
-- TOC entry 4936 (class 0 OID 0)
-- Dependencies: 221
-- Name: fixed_deposit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fixed_deposit_id_seq', 4, true);


--
-- TOC entry 4937 (class 0 OID 0)
-- Dependencies: 223
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transactions_id_seq', 25, true);


--
-- TOC entry 4938 (class 0 OID 0)
-- Dependencies: 217
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 15, true);


--
-- TOC entry 4764 (class 2606 OID 16406)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- TOC entry 4768 (class 2606 OID 16423)
-- Name: fixed_deposit fixed_deposit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fixed_deposit
    ADD CONSTRAINT fixed_deposit_pkey PRIMARY KEY (id);


--
-- TOC entry 4770 (class 2606 OID 16432)
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 4766 (class 2606 OID 16408)
-- Name: accounts uk6kplolsdtr3slnvx97xsy2kc8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk6kplolsdtr3slnvx97xsy2kc8 UNIQUE (account_number);


--
-- TOC entry 4772 (class 2606 OID 16434)
-- Name: transactions uk6plyfbm3wy6ds7hongoml5xbk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT uk6plyfbm3wy6ds7hongoml5xbk UNIQUE (transaction_id);


--
-- TOC entry 4762 (class 2606 OID 16396)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4775 (class 2606 OID 16445)
-- Name: transactions fk20w7wsg13u9srbq3bd7chfxdh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk20w7wsg13u9srbq3bd7chfxdh FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- TOC entry 4774 (class 2606 OID 16440)
-- Name: fixed_deposit fk438qamg02fakam12rbdbwrn67; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fixed_deposit
    ADD CONSTRAINT fk438qamg02fakam12rbdbwrn67 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4773 (class 2606 OID 16435)
-- Name: accounts fknjuop33mo69pd79ctplkck40n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fknjuop33mo69pd79ctplkck40n FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2026-09-11 13:16:18

--
-- PostgreSQL database dump complete
--

